<?php
echo "
				<div id= 'we-accept'>
					<h2><br>We Accept</h2>
					<ul>
						<li><img class='image10' alt='visa' src='../../images/Visa.png' /></li>
						<li><img class='image10' alt='paypal' src='../../images/Paypal.png' /></li>
						<li><img class='image10' alt='mastercard' src='../../images/MasterCard.png' /></li>
						<li><img class='image10' alt='stripe' src='../../images/stripe.png' /></li>
						<li><img class='image10' alt='jcb' src='../../images/jcb.png' /></li>
						<li><img class='image10' alt='discover' src='../../images/discover.png' /></li>
					</ul>
					</div>
				<div id= 'sign-up'>
					<img alt='newsletter' src='../../images/newsletter.png' />
					<h2>Sign Up For Our Newsletter</h2>
					<table class='email'>
						<tr>
							<th>Your Email Address</th>
							<td>Join</td>
						</tr>
					</table>
				</div>
";
?>