<?php
echo "<style>";
echo "body {
	margin: 0;
	background-color: #996633;
	font-family: Arial, Helvetica, sans-serif;
}";
echo "#authForm {	
	text-align: right;
	font-family: Arial, Helvetica, sans-serif;
	font-style: oblique;
	color: #1A186C; 
	float: right;
	margin-bottom: 0;
	display: block;
}";
echo "#authForm .button {
  		color: #780101;
		cursor: pointer;
		text-decoration: none;
		display: inline-block;
		text-align: center;
}";
echo "a.btn {
	text-decoration: none;
	color: #CC6600;
	border: 3px solid orange;
	margin: 200px 0 0 180px;
	padding: 10px 20px;
}";
echo "a.btn:hover {
	background-color: #CCFF99;
}";
echo "#wrapper {
	width: 1000px;
	margin: auto;
}";
echo "#banner {
	background-color: #FCF5EF;
	position: relative;
}";
echo "#banner img {
	width: 100%;
	margin-bottom: -0.3rem;
	position: relative;
}";
echo "#navigation {
	margin: 0;
	padding: 0;
	float: left;
	width: 25%;
	background-color: black;
	clear: both;
	margin-bottom: -0.9rem;
	font-family: Arial, Helvetica, sans-serif;
	list-style-type: none;
}";
echo "#navigation .current {
	text-decoration: underline;
	color: yellow;
}";
echo "#navigation ul {
	display: table;
	list-style-type: none;
}";
echo "#navigation ul li {
	display: block;
	text-align: left;
	position: relative;
	list-style-type: none;
	margin: 0;
	padding: 0;
}";
echo "#navigation ul li a {
	width: 100%;
	display: block;
	text-decoration: none;
	text-transform: uppercase;
	color: white;
	text-align: left;

}";
echo "#navigation ul li a:hover {
	color: #f2f2f2;
	background: maroon;
	text-align: left;
	width: 220px;
	margin: 0;
}";
echo "#navigation ul li ul.dropdown {
	background: gray;
	display: none;
	position: absolute;
	z-index: 999;
	left: 0;
	font-size: medium;
	text-align: left;
	list-style-type: none;
}";
echo "#navigation ul li:hover ul.dropdown {
	display: block;
	margin: 0;
	padding: 0;
	position: relative;
	left: 0;
	top: 0;
	visibility: visible;
	text-align: left;
	list-style-type: none;
}";
echo "#navigation ul li ul.dropdown li {
	display: block;
	text-align: left;
}";
echo "#social-media p {
	color: silver;
	text-align: center;
	margin: 50px 0 0 0;
}";
echo "#header {
	text-align: right;
	background-color: #FFCC66;
}";
echo "#header a {
	text-decoration: none;
}";
echo "#header p {
	margin-top: 0px;
}";
echo "#header ul li {
	display: inline-grid;
}";
echo "#content-area {
	background-color: #FFFFCC;
	display: block;
}";
echo "#content-area table {
	width: 70%;
	table-layout: auto;
}";
echo "#content-area .row {
	display: block;
}";
echo "#content-area table .td1 {
	width: 65%;
}";
echo "#content-area table .td2 {
	width: 65%;
}";
echo "#content-area table .td1 img {
	height: auto;
}";
echo "#content-area table .td2 img {
	height: auto;
}";
echo "#content-area img {
	float: left;
	width: 100%;
	height: auto;
}";
echo "#content-area3 p{
	display: block;
	margin-block: 41px;
}";
echo ".column {
	float: left;
  	margin-bottom: 0;
	display: inline-block;
}";

echo ".column img {
  opacity: 0.8;
  cursor: pointer;
  display: inline-block;
}";

echo ".column img:hover {
  opacity: 1;
}";

echo ".container {
  position: relative;
  float: right;
  padding-top: 0;
  display: none;
}";

echo "#imgtext {
  position: absolute;
  color: white;
}";

echo ".closebtn {
  position: absolute;
  color: white;
  cursor: pointer;
}";
echo "#bottom-bar {
	background-color: #FFCC66;
	overflow: hidden;
}";
echo "#we-accept {
	display: inline;
}";
echo "#sign-up {
	display: inline;
}";
echo "#we-accept ul li {
	display: inline;
}";
echo "#footer {
	margin: 0;
	text-align: center;
	font-size: large;
	width: 100%;
	height: 20px;
	line-height : 10px;
	vertical-align: middle;
	color: linen;
	background-color: maroon;
}";
echo "#footer .content {
	margin-top: 0;
	display: inline;
}";
echo "#footer a {
	margin-left: 30px;
	color: #FFCC66;
	text-decoration: none;
}";
echo "#footer a:visited {
	color: #FFCC66;
}";
echo "#footer a:hover {
	color: green;
}";
echo "</style>";
?>
